In [5]:
import numpy as np
import pandas as pd
import matplotlib as plt
import math

In [6]:
#Variables:

#Rz - Rotation matrix through Z by angle O_GAST
#R_dot_z - Newtonian notation for differential w.r.t time of R_z
#w_cross = rotation rate of the earth in radians per second (2Pi radians/86400 seconds)
#X_f = np.array([x_f,y_f,z_f]) #instantaneous position vector in planet fixed reference frame 
#v_f = np.array([u_f,v_f,w_f]) #Instantaneous velocity vector in the planet fixed reference frame 
#Re = Radius of the earth (avg between polar and equatorial)
#OGAST = Greenwich Apparent Siderial Time

#To Define in the function :
#X_i = np.array([x_i,y_i,z_i]) #instantaneous position vector in inertial reference frame 
#v_i = np.array([u_i,v_i,w_i]) #Instantaneous velocity vector in the inertial reference frame 
GM = 398600.4415 #Km^3 s^-2
Re = 6378.137 #Km
w_cross = (2*(np.pi) / 86400) #Rad/Sec

In [8]:
x_i= float(input('x:')) #in km
y_i= float(input('y:')) #in km
z_i= float(input('z:')) #in km
u_i= float(input('\nu:')) #in km/s
v_i= float(input('v:')) #in km/s
w_i= float(input('w:')) #in km/s
d= float(input('days since J2000 *IN DECIMAL FORMAT*:')) #in days

#Making the coordinates into the relevant vectors
X_i = np.array([x_i,y_i,z_i])
V_i = np.array([u_i,v_i,w_i])

print ('\nspecified poisiton vector in inertial frame:',X_i)
print ('specified velocity vector in inertial frame:',V_i)

OGAST = 280.4606+360.9856473662*d #in degrees - where d is days since J2000 epoch in decimal format

x:-7134.401598
y:-1344.205350
z:2616.199171

u:2.737023
v:-2.641275
w:6.099438
days since J2000 *IN DECIMAL FORMAT*:69

specified poisiton vector in inertial frame: [-7134.401598 -1344.20535   2616.199171]
specified velocity vector in inertial frame: [ 2.737023 -2.641275  6.099438]


In [41]:
#Constructing a rotation matrix for position vectors
R_z = [[np.cos(OGAST),  np.sin(OGAST),  0],
      [-np.sin(OGAST), np.cos(OGAST),  0],
      [0,              0,              1]]
         
print(R_z)

[[0.6824929890652967, -0.7308921397010073, 0], [0.7308921397010073, 0.6824929890652967, 0], [0, 0, 1]]


In [42]:
#Constructing a rotation matrix for velocity vectors
mat_a = [[np.sin(OGAST),  -np.cos(OGAST),  0],
            [np.cos(OGAST), np.sin(OGAST),   0],
            [0,              0,              1]]

R_dot_z = np.dot(w_cross,mat_a)
print(R_dot_z)

[[-5.31519763e-05 -4.96322908e-05  0.00000000e+00]
 [ 4.96322908e-05 -5.31519763e-05  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  7.27220522e-05]]


In [43]:
#Converted position coordinates from eci to ecef = multiply coordinates by rotation matrix

X_f = np.dot(X_i,R_z)
print(X_f)

[-5851.64819627  4297.06732221  2616.199171  ]


In [44]:
#The differenetial of Xf (i.e. v_f) = (R_dot_z *X_i) + (R_z *V_i) --Product rule

V_f = (np.dot(R_dot_z, X_i)) + (np.dot(R_z, V_i))
print(V_f)

[ 4.24440968 -0.0848326   6.28969337]


In [46]:
ECI_2_ECEF = pd.DataFrame ({"Coordinate":["x","y","z","u","v","w"], 
                            "ECI": [X_i[0],X_i[1],X_i[2],V_i[0],V_i[1],V_i[2]],
                            "ECEF":[X_f[0],X_f[1],X_f[2],V_f[0],V_f[1],V_f[2]]})

print ('Table of results:')
ECI_2_ECEF

Table of results:


Coordinate          ECI         ECEF
0          x -7134.401598 -5851.648196
1          y -1344.205350  4297.067322
2          z  2616.199171  2616.199171
3          u     2.737023     4.244410
4          v    -2.641275    -0.084833
5          w     6.099438     6.289693