In [1]:
################# STARTING STATION VISIBILITY ###########

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
GM = 398600.4415 #km^3 s^-2
RE = 6367 #km - Radius of the Earth

In [3]:
# Determination of  station-satellite visibility
# A key element of mission desing and planning is to determine:
#* When a satellite will appear above the horizon at a tracking station
#* How long the pass will last#
#* The azimuth and elevation of the satellite at any point in the pass
#
# The first problem to solve here is, given tracking station coordinates (Lambda_deg,Phi_deg) and the satellite ECEF position
# whether or not the satellite is visible

In [4]:
# Steps:

# Given r_p and r_s(t) in ECEF components compute (Phi_deg,Lambda_deg) for P = f(r_p)
# Calculate ECEF components of (e,n,u)

# Calculate r_ss = r_s - r_p
# Normalize r_ss -> unit_vector_r_ss  = r_ss/mag_r_ss

# project r_ss onto e,n,u -> this gives unit_vector_rss in topocentric basis
# r_ss_e = unit_vector_r_ss * e
# r_ss_n = unit_vector_r_ss * n
# r_ss_u = unit_vector_r_ss * u

#Let elev = satellite elevation angle 
# elev = np.arcsin(r_ss_u/1)

# Let alpha = azimuth (direction from the north)
# alpha = math.atan2(r_ss_e, r_ss_n)

# Let m_a = site mask angle 
# If m_a-elev > 0, the satellite is visible to ground station

In [5]:
#r_p = tracking station position vector (ECEF) (from the centre of mass of the Earth)
#r_s = satellite position vector (ECEF)
#r_ss = station-satellite vector 

In [6]:
# A topocentric basis is defined by (Phi_deg,Lambda_deg)
# Where Phi is Lat and Lambda is Long
# and three orthogonal unit vectros e,n,u (east, north, up)

# Phi_deg= float(input('Latitude of satellite:')) #in degrees
# Lambda_deg= float(input('Longitude:')) #in degrees

Phi_deg = 19.817211
Lambda_deg = -100.670114

In [7]:
#If the radius of P is the ecef position vector:
# u = unit vector of radius of P  = radius P vector/ magnitude of the vector P
# e,n,u are functions of (Phi,Lambda)

# Need to define the ECEF basis unit vectors i,j,k first

i = np.array([1,0,0])
j = np.array([0,1,0])
k = np.array([0,0,1])

#Defining the e,n,u vectors as defined in appendix 10

e = (-np.sin(Lambda_deg*i)) + (np.cos(Lambda_deg)*j)

    
#Splitting n into smaller terms
n_a = -np.cos(Lambda_deg)
n_b = np.sin(Phi_deg)
n_c = n_a*n_b

n_d = -np.sin(Lambda_deg)
n_e = np.sin(Phi_deg)
n_f = n_d*n_e

n = np.array(n_c*i) + (n_f*j) + (np.cos(Phi_deg*k))


#Splitting u into smaller terms

u_a = np.cos(Lambda_deg)
u_b = np.cos(Phi_deg)
u_c  = u_a*u_b

u_d = np.sin(Lambda_deg)
u_e = np.cos(Phi_deg)
u_f = u_d*u_e

u = (u_c*i) + (u_f*j) + (np.sin(Phi_deg)*k)

# 3 unit vectors: east north up
print(e)
print(n)    
print(u)  



[0.13870047 0.99033438 0.        ]
[0.18440234 1.11422787 0.56723227]
[ 0.56174961 -0.07867538  0.82355786]


In [8]:
#Defining r_s (needs to be part of forloop
              # as this is updated with every new dt)

# x_s= float(input('satellite vector x-coord.:')) #in degrees
# y_s= float(input('satellite vector y-coord:')) #in degrees
# z_s= float(input('satellite vector z-coord:')) #in degrees


#Following coordinates taken from KEP2CAR
x_s = -7134.4015980671975
y_s = -1344.2053503962836
z_s = 2616.199171181745

r_s = np.array([x_s,y_s,z_s])
print(r_s)

[-7134.40159807 -1344.2053504   2616.19917118]


In [55]:
#Defining r_p (static - does not change with each new dt)

# x_p= float(input('station vector x-coord.:')) #in degrees
# y_p= float(input('station vector y-coord:')) #in degrees
# z_p= float(input('station vector z-coord:')) #in degrees


#Following coordinates (made up)
###GET A HOLD OF SOME ACTUAL ONES###
x_p = 958506.011
y_p = 4556367.375
z_p = 4344627.164

r_p = np.array([x_p,y_p,z_p])
print(r_p)

[ 958506.011 4556367.375 4344627.164]


In [56]:
#Calculating Lat Long of Station xyz coords:

In [57]:
#Creating empty lists for lat/long/height
p_Lambda_rad_array = [0]
p_long_array = [0]

p_Phi_rad_array = [0]
p_lat_array = [0]

p_r_mag_array = [0]
p_h_array = [0]

In [77]:
#Calculating Longitude
#Calculating Long in Radians
p_Lambda_rad_array = np.arctan2(y_p,x_p) 

#Converting to degrees
p_long_array = p_Lambda_rad_array * (180/np.pi)
print ('Station Longitude:',p_long_array) #UNHASH TO CHECK

Station Longitude: 78.12012299743195


In [78]:
#Calculating Latitude
#Calculating Lat in Radians
p_Phi_rad_array = np.arctan(z_p/(np.sqrt(x_p**2+y_p**2))) 

#Converting to degrees
p_lat_array = p_Phi_rad_array * (180/np.pi)
print ('Station Latitudes:',p_lat_array) #UNHASH TO CHECK

Station Latitudes: 43.018086242448426


In [84]:
#Calculating the radius vector magnitude from the centre of the earth to the station

p_r_mag_array = np.sqrt((x_p**2)+(y_p**2)+(z_p**2))
# Now finding the height of the station above the height of the Earth
p_h_array = (p_r_mag_array) - (RE*1000) 

print('height in metres:',p_h_array)


height in metres: 1280.9786671791226


In [85]:
print('Station height in metres above the surface of the Earth:',p_h_array)
print ('Station Latitude:',p_lat_array)
print ('Station Longitude:',p_long_array)

Station height in metres above the surface of the Earth: 1280.9786671791226
Station Latitude: 43.018086242448426
Station Longitude: 78.12012299743195


In [86]:
##### TODO # Calculate ECEF components of (e,n,u) ###
### Still missing this but it all works ?

In [90]:
#Calculating r_ss:The station-satellite vector

r_ss = r_s - r_p
print(r_ss)

[ -965640.41259807 -4557711.5803504  -4342010.96482882]


In [91]:
#Normalizing r_ss
r_ss_norm = r_ss / np.linalg.norm(r_ss)
print(r_ss_norm)

[-0.15162674 -0.71566076 -0.68179103]


In [92]:
#Projecting r_ss_norm onto e,n,u
# This gives the components of r_ss in the topocentric basis

r_ss_e = np.dot(r_ss_norm,e)
r_ss_n = np.dot(r_ss_norm,n)
r_ss_u = np.dot(r_ss_norm,u)

print(r_ss_e)
print(r_ss_n)
print(r_ss_u)

-0.7297741542806451
-1.212103358983616
-0.5903657408237153


In [98]:
#Let Theta = satellite elevation angle 
Theta = np.arcsin(r_ss_u)
elevation = Theta*(180/np.pi)
print('Elevation angle to the horizon (degrees):',elevation)
#I think this is in radians ?

Elevation angle to the horizon (degrees): -36.182966575382146


In [104]:
# Let alpha = azimuth (direction from the north)
#Defining the site mask angle (alpha)
alpha = math.atan2(r_ss_e, r_ss_n)
azimuth = alpha*(180/np.pi)
print('Direction from the north (degrees):',azimuth)

Direction from the north (degrees): -148.94900852900324


In [106]:
#Let gamma = site mask angle (depends on local geography and equipment)
gamma = 13 #just made this up

In [108]:
if elevation-gamma > 0:
    print ('the satellite is visible')
    print ('Direction from the north (degrees):',azimuth)
else: print ('the satellite is not visible')

the satellite is not visible
